---
output:
  bookdown::pdf_document2:
    toc: false
    keep_tex: false
    fig_caption: yes
title: "Title"
author: Author
bibliography: "references.bib"
csl: apa.csl # by default: Chicago style
header-includes:
- \usepackage{float}
- \usepackage{multirow}
- \usepackage{xcolor} 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.lp="fig:")

# install.packages("tinytex", repos = "https://cloud.r-project.org" ) if debug needed?

# library(namelibrary) for the R library

# http://rmarkdown.rstudio.com
# echo = TRUE <- makes all next cmds appear

```
\newcommand{\rocco}[1]{\textcolor{red}{{Rocco:}#1}} <!-- <- this is a command to appear in pdf -->
<!-- command not to appear in pdf -->

# Introduction and Questions

@zhang2004 cites and refers to @schelling1978 for his prominent influence on threshold and tipping model, still then elaborates on a model based on random utility with single-peaked function and $\beta$. How much can a rational model which uses peak of utility and probability of choice be considered to rely on Schelling's threshold model?\
What is the relation between random utility models and threshold models?\
\

- @zhang2004 assumes an entire world, not empty patches, so that $utility = 1$ at 50% is because $4/8$ of agents are of similar ethnicity (plus the peak function). To replicate his model there should be not empty space. @bruch2006 models with $15%$ empty patches. Should our world have not empty patches, so to maximize utility? This can allow also to test density effects on satisfaction and not bias on concentration calculation.

## Component of probability of the choice

- Object of choice: neighborhood
- Choice: relocate to a neighborhood
- Utility: payoff one is likely to accept to make the choice, i.e. to relocate to one neighborhood (which implies to stay on the same neighborhood). In @zhang2004 it is made up of:
  - deterministic component $U$: how much people desire/value one preference  in order to make the choice, e.g. degree of ethnic concentration (e.g. max utility = 1 at 100% similars). @zhang2004 uses a single-peaked function (vs maximization).
  - random term $\epsilon$ that refers to other characteristics of the option, i.e. the neighborhood, that influence the payoff to choose the neighborhood although not related to the deterministic component. In regression models  this is the random  error terms. Random utility models in abm recreate with the exponential function, so that not always the best option according to the deterministic component is taken.
- Probability of the choice: $\beta u (.) + \epsilon$\
$\beta$ is a parameter indicating how much the random term is important modeled as a positive constant. The lower is \$beta\, the higher is random term $\epsilon$, i.e. other random characteristics, are relevant to choose one neighborhood. The higher is $\beta$, the lower will be the importance of random term $\epsilon$ and higher the importance of deterministic utility component to make a choice, i.e. moving to the neighborhood.
\
- Given the existence of an ideal payoff to make a choice $u$, why should someone give more importance to that dimension over the other, that is, why should $\beta$ vary among individuals? An answer in @esser2010 is social, educational, economic capital. For instance:
  - The lower an agent speaks a language, the higher for ethnic homophily would be  $\beta_{ethnic}$;
  - the higher is social mobility intention, the higher the wealth (socio-economic status) of the neighborhood would be $\beta_{status}$
  - the higher the need to associate with people sharing the same values of local community (receiving context in Esser [@esser2010] (e.g. political orientations, norm beliefs...), the higher 
- Costs of relocation can be included as costs that hinder relocation despite high probability to choose. This can be one application of  @esser2010's definition of costs as limit to the investment on the receving context option (although in the ethnic population, but it can be extended). In @esser2010 costs is loosely derived from social, economic and cultural capital milieu, e.g. risk of social exclusion from in-group, but economic costs of relocation can be one simple implementation now.


# Aim of the paper

- The conceptual difference between $u$ and  $\beta$ should be $u$: what is the ideal point (payoff) to make the choice and $\beta$ how important is that component to people to make a choice. The paper could focus on the interplay between different utility functions at ethnic group level and the individual importance for each of them. This would allow to test how segregation can emerge from the interplay of different homophily preferences.
  - The model could be initialized with correlations from data, as Andreas suggested, plus literature (e.g. right-wing and anti-diversity/migrant attitude)
- Given the interplay of homophily preferences, to compare the difference between threshold models and random utility models with single peaked function. It makes sense to consider $\beta$ would apply equally to threshold models and single-peaked function, as well as the inclusion of randomness in a pure Schelling-type model. Check @bruch2006 who should have had similar  interest.
  - This aim/study would make a straight connection with the ACS paper and its conclusion
- The model can address the question why $\beta$, the importance of one characteristic of the neighborhood, would change depending on the needs (characteristics) of the individuals (households)
- The model can address the question of how costs interact with needs and preferences (economic capital) of individuals.
  - Both points above (need $\rightarrow$ change in $\beta$) and costs of relocation can be linked to @esser2010 focus on capital theory. Relative group size and ethnic boundary making in @esser2010 are supposed to influence probability to make a choice. As linking to the ACS paper, they realize into relative group size and symbolic boundary making through homophily preferences.  
  This would foster the linkage Schelling-Esser of the general project agenda.
- As in the Schelling's model [@schelling1969;@schelling1971], there is not question on why preferences for similar exist. While in the ACS paper we extended the model by including different dimensions of similarity. Extension to rational models as this would benefit understanding of different homophily preferences through their explicative reasons.

- The formula $\beta u (.) + \epsilon$ should become something like $$N_{e} U_{e} + N_{v} U_{v} + N_{s} U_{s} - C$$ where $N$ =  needs, $C$ = costs and $e,v,s$ the ethnic, value and socio-economic status dimension. The random term $\epsilon$ is implemented through the exponential function.

# Limits

- Both $u$ and $\beta$ can vary across individuals, but the model would explode in its complexity
- Even if we consider households as agents who make a choice, the decision to relocate can be the product of negotiation of people in that household. Too complicated to be included

<!-- read @Brock2001, @Brock1997 -->

# References
